# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto

require 'google/protobuf'

require 'model_pb'
require 'google/api/annotations_pb'
require 'protoc-gen-swagger/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("collector.proto", :syntax => :proto3) do
    add_message "jaeger.api_v2.PostSpansRequest" do
      optional :batch, :message, 1, "jaeger.api_v2.Batch"
    end
    add_message "jaeger.api_v2.PostSpansResponse" do
    end
  end
end

module Jaeger
  module ApiV2
    PostSpansRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.PostSpansRequest").msgclass
    PostSpansResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.PostSpansResponse").msgclass
  end
end
