# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/duration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("model.proto", :syntax => :proto3) do
    add_message "jaeger.api_v2.KeyValue" do
      optional :key, :string, 1
      optional :v_type, :enum, 2, "jaeger.api_v2.ValueType"
      optional :v_str, :string, 3
      optional :v_bool, :bool, 4
      optional :v_int64, :int64, 5
      optional :v_float64, :double, 6
      optional :v_binary, :bytes, 7
    end
    add_message "jaeger.api_v2.Log" do
      optional :timestamp, :message, 1, "google.protobuf.Timestamp"
      repeated :fields, :message, 2, "jaeger.api_v2.KeyValue"
    end
    add_message "jaeger.api_v2.SpanRef" do
      optional :trace_id, :bytes, 1
      optional :span_id, :bytes, 2
      optional :ref_type, :enum, 3, "jaeger.api_v2.SpanRefType"
    end
    add_message "jaeger.api_v2.Process" do
      optional :service_name, :string, 1
      repeated :tags, :message, 2, "jaeger.api_v2.KeyValue"
    end
    add_message "jaeger.api_v2.Span" do
      optional :trace_id, :bytes, 1
      optional :span_id, :bytes, 2
      optional :operation_name, :string, 3
      repeated :references, :message, 4, "jaeger.api_v2.SpanRef"
      optional :flags, :uint32, 5
      optional :start_time, :message, 6, "google.protobuf.Timestamp"
      optional :duration, :message, 7, "google.protobuf.Duration"
      repeated :tags, :message, 8, "jaeger.api_v2.KeyValue"
      repeated :logs, :message, 9, "jaeger.api_v2.Log"
      optional :process, :message, 10, "jaeger.api_v2.Process"
      optional :process_id, :string, 11
      repeated :warnings, :string, 12
    end
    add_message "jaeger.api_v2.Trace" do
      repeated :spans, :message, 1, "jaeger.api_v2.Span"
      repeated :process_map, :message, 2, "jaeger.api_v2.Trace.ProcessMapping"
      repeated :warnings, :string, 3
    end
    add_message "jaeger.api_v2.Trace.ProcessMapping" do
      optional :process_id, :string, 1
      optional :process, :message, 2, "jaeger.api_v2.Process"
    end
    add_message "jaeger.api_v2.Batch" do
      repeated :spans, :message, 1, "jaeger.api_v2.Span"
      optional :process, :message, 2, "jaeger.api_v2.Process"
    end
    add_message "jaeger.api_v2.DependencyLink" do
      optional :parent, :string, 1
      optional :child, :string, 2
      optional :call_count, :uint64, 3
      optional :source, :string, 4
    end
    add_enum "jaeger.api_v2.ValueType" do
      value :STRING, 0
      value :BOOL, 1
      value :INT64, 2
      value :FLOAT64, 3
      value :BINARY, 4
    end
    add_enum "jaeger.api_v2.SpanRefType" do
      value :CHILD_OF, 0
      value :FOLLOWS_FROM, 1
    end
  end
end

module Jaeger
  module ApiV2
    KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.KeyValue").msgclass
    Log = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Log").msgclass
    SpanRef = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.SpanRef").msgclass
    Process = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Process").msgclass
    Span = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Span").msgclass
    Trace = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Trace").msgclass
    Trace::ProcessMapping = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Trace.ProcessMapping").msgclass
    Batch = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Batch").msgclass
    DependencyLink = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.DependencyLink").msgclass
    ValueType = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.ValueType").enummodule
    SpanRefType = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.SpanRefType").enummodule
  end
end
