# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

require 'google/protobuf'

require 'model_pb'
require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/duration_pb'
#require 'protoc-gen-swagger/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("query.proto", :syntax => :proto3) do
    add_message "jaeger.api_v2.GetTraceRequest" do
      optional :trace_id, :bytes, 1
    end
    add_message "jaeger.api_v2.SpansResponseChunk" do
      repeated :spans, :message, 1, "jaeger.api_v2.Span"
    end
    add_message "jaeger.api_v2.ArchiveTraceRequest" do
      optional :trace_id, :bytes, 1
    end
    add_message "jaeger.api_v2.ArchiveTraceResponse" do
    end
    add_message "jaeger.api_v2.TraceQueryParameters" do
      optional :service_name, :string, 1
      optional :operation_name, :string, 2
      map :tags, :string, :string, 3
      optional :start_time_min, :message, 4, "google.protobuf.Timestamp"
      optional :start_time_max, :message, 5, "google.protobuf.Timestamp"
      optional :duration_min, :message, 6, "google.protobuf.Duration"
      optional :duration_max, :message, 7, "google.protobuf.Duration"
      optional :search_depth, :int32, 8
    end
    add_message "jaeger.api_v2.FindTracesRequest" do
      optional :query, :message, 1, "jaeger.api_v2.TraceQueryParameters"
    end
    add_message "jaeger.api_v2.GetServicesRequest" do
    end
    add_message "jaeger.api_v2.GetServicesResponse" do
      repeated :services, :string, 1
    end
    add_message "jaeger.api_v2.GetOperationsRequest" do
      optional :service, :string, 1
      optional :span_kind, :string, 2
    end
    add_message "jaeger.api_v2.Operation" do
      optional :name, :string, 1
      optional :span_kind, :string, 2
    end
    add_message "jaeger.api_v2.GetOperationsResponse" do
      repeated :operationNames, :string, 1
      repeated :operations, :message, 2, "jaeger.api_v2.Operation"
    end
    add_message "jaeger.api_v2.GetDependenciesRequest" do
      optional :start_time, :message, 1, "google.protobuf.Timestamp"
      optional :end_time, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "jaeger.api_v2.GetDependenciesResponse" do
      repeated :dependencies, :message, 1, "jaeger.api_v2.DependencyLink"
    end
  end
end

module Jaeger
  module ApiV2
    GetTraceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetTraceRequest").msgclass
    SpansResponseChunk = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.SpansResponseChunk").msgclass
    ArchiveTraceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.ArchiveTraceRequest").msgclass
    ArchiveTraceResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.ArchiveTraceResponse").msgclass
    TraceQueryParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.TraceQueryParameters").msgclass
    FindTracesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.FindTracesRequest").msgclass
    GetServicesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetServicesRequest").msgclass
    GetServicesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetServicesResponse").msgclass
    GetOperationsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetOperationsRequest").msgclass
    Operation = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.Operation").msgclass
    GetOperationsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetOperationsResponse").msgclass
    GetDependenciesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetDependenciesRequest").msgclass
    GetDependenciesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.GetDependenciesResponse").msgclass
  end
end
