# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sampling.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
#require 'protoc-gen-swagger/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sampling.proto", :syntax => :proto3) do
    add_message "jaeger.api_v2.ProbabilisticSamplingStrategy" do
      optional :samplingRate, :double, 1
    end
    add_message "jaeger.api_v2.RateLimitingSamplingStrategy" do
      optional :maxTracesPerSecond, :int32, 1
    end
    add_message "jaeger.api_v2.OperationSamplingStrategy" do
      optional :operation, :string, 1
      optional :probabilisticSampling, :message, 2, "jaeger.api_v2.ProbabilisticSamplingStrategy"
    end
    add_message "jaeger.api_v2.PerOperationSamplingStrategies" do
      optional :defaultSamplingProbability, :double, 1
      optional :defaultLowerBoundTracesPerSecond, :double, 2
      repeated :perOperationStrategies, :message, 3, "jaeger.api_v2.OperationSamplingStrategy"
      optional :defaultUpperBoundTracesPerSecond, :double, 4
    end
    add_message "jaeger.api_v2.SamplingStrategyResponse" do
      optional :strategyType, :enum, 1, "jaeger.api_v2.SamplingStrategyType"
      optional :probabilisticSampling, :message, 2, "jaeger.api_v2.ProbabilisticSamplingStrategy"
      optional :rateLimitingSampling, :message, 3, "jaeger.api_v2.RateLimitingSamplingStrategy"
      optional :operationSampling, :message, 4, "jaeger.api_v2.PerOperationSamplingStrategies"
    end
    add_message "jaeger.api_v2.SamplingStrategyParameters" do
      optional :serviceName, :string, 1
    end
    add_enum "jaeger.api_v2.SamplingStrategyType" do
      value :PROBABILISTIC, 0
      value :RATE_LIMITING, 1
    end
  end
end

module Jaeger
  module ApiV2
    ProbabilisticSamplingStrategy = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.ProbabilisticSamplingStrategy").msgclass
    RateLimitingSamplingStrategy = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.RateLimitingSamplingStrategy").msgclass
    OperationSamplingStrategy = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.OperationSamplingStrategy").msgclass
    PerOperationSamplingStrategies = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.PerOperationSamplingStrategies").msgclass
    SamplingStrategyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.SamplingStrategyResponse").msgclass
    SamplingStrategyParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.SamplingStrategyParameters").msgclass
    SamplingStrategyType = Google::Protobuf::DescriptorPool.generated_pool.lookup("jaeger.api_v2.SamplingStrategyType").enummodule
  end
end
